# Use an official Node.js runtime as a parent image
FROM node:alpine

RUN apk update && apk add python3 make


# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in package.json
RUN npm install
# Install the bcrypt modules for the machine
RUN npm install bcrypt

# Install the Prisma client and copy the engine binary
RUN npm install prisma@4.3.1

# Expose port 3000 for the container
# EXPOSE 3000

# Define the command to run the app
CMD ["npm", "run", "watch"]
